set nocompatible
filetype off " vundle needs this

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"Plugin 'Shougo/neocomplete.vim.git'
"Plugin 'wellle/targets.vim.git'
"Plugin 'bronson/vim-visual-star-search'
Plugin 'AndrewRadev/linediff.vim'
Plugin 'AndrewRadev/writable_search.vim.git'
Plugin 'SirVer/ultisnips.git'
Plugin 'altercation/vim-colors-solarized.git'
Plugin 'elixir-editors/vim-elixir'
Plugin 'fatih/vim-go.git'
Plugin 'fholgado/minibufexpl.vim.git'
Plugin 'inkarkat/vim-ingo-library'
Plugin 'inkarkat/vim-mark'
Plugin 'kien/ctrlp.vim.git'
Plugin 'majutsushi/tagbar.git'
Plugin 'nvie/vim-flake8'
Plugin 'rking/ag.vim'
Plugin 'scrooloose/nerdtree.git'
Plugin 'scrooloose/syntastic.git'
Plugin 'sotte/presenting.vim'
Plugin 'tobyS/vmustache.git'
Plugin 'tpope/vim-fugitive.git'
Plugin 'tpope/vim-unimpaired.git'

call vundle#end()            " required
filetype plugin indent on    " required

set mouse=a
set ttymouse=xterm2

syntax on
set number
"set relativenumber
set ruler
set enc=utf-8
 
set hlsearch
set incsearch
set smartcase
set history=1000

"set laststatus=2 " always show what file you're on

set backspace=2 " make backspace work like most other apps
set ts=4
set sw=4

"set smarttab
set expandtab
set smartindent
set noshowmatch

set scrolloff=4 " show 4 lines around where you are

set undolevels=100

set hidden
set nobackup
set directory=~/.vim/directory
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.log,*.gz

set lazyredraw " otherwise using relativenumber is slow in terminal

set cc=95

"nmap <F5> :GoTest<CR>
nmap <F6> :set relativenumber!<CR>
nmap <F7> :Gblame<CR>
nmap <F8> :TagbarToggle<CR>
map <F9> :NERDTreeToggle<CR>

augroup filetype
    autocmd BufNewFile,BufRead *.raml set filetype=yaml
    autocmd BufNewFile,BufRead *.md set filetype=markdown
augroup END

augroup indent
    autocmd FileType json setlocal ts=2 sw=2 expandtab
    autocmd FileType yaml setlocal ts=4 sw=4 expandtab
    autocmd FileType ruby setlocal ts=2 sw=2 expandtab
augroup END

"TODO clean up autogroups
au BufNewFile,BufRead *.py
    \ setlocal tabstop=4
    \ | setlocal softtabstop=4
    \ | setlocal shiftwidth=4
    \ | setlocal textwidth=79
    \ | setlocal expandtab
    \ | setlocal autoindent
    \ | setlocal fileformat=unix

if has("gui_running")
	colorscheme desert
	set guifont=terminus
	set go-=T
elseif &diff
	colorscheme desert
else
	set background=dark
	colorscheme solarized
endif

let mapleader=","

let g:UltiSnipsSnippetsDir = '~/.vim/UltiSnips/'

let g:mwDefaultHighlightingPalette = 'maximum'

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"

let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }

let g:ag_working_path_mode="r"

" TODO reorganize this??

let s:uname = system("uname -s")

if s:uname == "Darwin"
    let g:tagbar_ctags_bin = '/usr/local/opt/ctags/bin/ctags'
elseif s:uname == "Linux"
    let g:tagbar_ctags_bin = '/usr/bin/ctags'
endif

"make quickfix window not huge
au FileType qf call AdjustWindowHeight(3, 10)
function! AdjustWindowHeight(minheight, maxheight)
    exe max([min([line("$")+1, a:maxheight]), a:minheight]) . "wincmd _"
endfunction
