#!/bin/sh

if git status --porcelain|grep "^\w"; then
    echo "You've got some shit already added..."
    exit 1
fi

NAME="spacer-commit-"`head /dev/random | md5`
touch $NAME
git add $NAME
git commit -m "--------------------------------------------------"
